# Generated by Django 4.2.7 on 2023-12-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPT',
            fields=[
                ('Dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SALGRADE',
            fields=[
                ('Grade', models.IntegerField(primary_key=True, serialize=False)),
                ('Losal', models.IntegerField()),
                ('Hisal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('Emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('Hgr', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Sal', models.IntegerField()),
                ('Comm', models.IntegerField()),
                ('Dept_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
