# Generated by Django 4.2.7 on 2023-12-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Hgr',
            new_name='Mgr',
        ),
    ]
