# Generated by Django 4.2.7 on 2023-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_hgr_emp_mgr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMP',
        ),
    ]
