# Generated by Django 4.2.7 on 2023-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Adr',
            field=models.CharField(default='Adr', max_length=100),
        ),
    ]
