# Generated by Django 4.2.7 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dept_adr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='Adr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
