# Generated by Django 4.2.7 on 2023-12-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_emp_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Dept_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dept'),
        ),
    ]
